name: after_frame
description: "AfterFrame · 余帧 — 将视频里的珍贵瞬间转化为动态记忆。"
publish_to: 'none'
version: 0.7.5+13

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  video_player: ^2.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true
  image_path: assets/icon/app_icon_launcher_opaque.png
  remove_alpha_ios: true
  adaptive_icon_background: "#DCF947"
  adaptive_icon_foreground: assets/icon/app_icon_launcher.png
  adaptive_icon_foreground_inset: 0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/logo.png
